# This template workflow is disabled to avoid editor warnings in the main repo.
# Copy it to .github/workflows/ in your new project and configure secrets.
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI (Template)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present
