name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build --if-present

      - name: Lint
        run: pnpm run lint

      - name: Smoke test (external)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        env:
          SMOKE_URL: ${{ secrets.SMOKE_URL }}
        run: pnpm run smoke

      - name: Check .env.example required keys
        run: |
          required=(NEXT_PUBLIC_FIREBASE_API_KEY NEXT_PUBLIC_FIREBASE_PROJECT_ID)
          missing=0
          for k in "${required[@]}"; do
            if ! grep -q "^${k}=" .env.example; then
              echo "Missing $k in .env.example"
              missing=1
            fi
          done
          if [ $missing -ne 0 ]; then
            echo "Please populate .env.example with required keys."
            exit 1
          fi
